# Generated by Django 3.0.7 on 2020-06-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(choices=[('EARPHONE', 'earphone'), ('HEADPHONE', 'headphone'), ('LAPTOP', 'laptop')], max_length=20)),
                ('product_description', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by', models.CharField(max_length=20, null=True)),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('product_quantity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('product_price', models.IntegerField(null=True)),
                ('product_status', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
